# Generated by Django 4.1.4 on 2022-12-15 13:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_email_body_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body_upload',
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
